name: Deploy FastAPI App to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  # Needed for Workload Identity Federation

    steps:
    # ------------------------------
    # Step 1: Checkout the repo
    # ------------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # ------------------------------
    # Step 2: Authenticate with GCP
    # ------------------------------
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/469370512556/locations/global/workloadIdentityPools/github-pool/providers/github'
        service_account: 'gha-deployer@devproject212.iam.gserviceaccount.com'

    # ------------------------------
    # Step 3: Install Python dependencies
    # ------------------------------
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # ------------------------------
    # Step 4: Deploy to App Engine
    # ------------------------------
    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v2'
      with:
        project_id: 'devproject212'
        deliverables: 'app.yaml'
