name: Deploy Flask App to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Authenticate with your GCP Service Account
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # Deploy to App Engine
    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v2'
      with:
        project_id: 'devproject212'
        deliverables: 'app.yaml'

    # (Optional) Run a test against the deployed app
    - name: Test deployment
      run: curl "${{ steps.deploy.outputs.version_url }}"
