name: Deploy Flask App to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Authenticate with GCP via Workload Identity Federation
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/469370512556/locations/global/workloadIdentityPools/github-pool/providers/github'
        service_account: 'gha-deployer@devproject212.iam.gserviceaccount.com'

    # Deploy to App Engine
    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v2'
      with:
        project_id: 'devproject212'
        deliverables: 'app.yaml'
